apps/hcmfront_app/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import RedirectView
from views.account import LogoutView  
from views.reserva import index as  ireserva, reservation_notification, confirm_reservation_request,reservadelete, reservaformedit, reservar, get_salas_reserva, reserva_resume, ReservaCreate, confirm_reservation
from django.contrib.auth.decorators import permission_required
from views.home import index as ihome
from views.sala import RoomList, RoomCreate, RoomEdit, RoomDelete
from views.insumo import index as iinsumo, supply_new, supply_edit, supply_delete
from views.usuario import UserList, UserCreate, UserDelete
from django.contrib.auth.views import login

urlpatterns = [
    url(r'^accounts/login/$', login, {'template_name' : 'accounts/login.html'}, name='loginf'),
    url(r'^accounts/logout/$', LogoutView.as_view(), name="logout"),
    url(r'^reserva$', ireserva, name="reservas"),
    url(r'^reserva/confirm/(?P<pk>\d+)$', confirm_reservation, name="confirm_reservation"),
    url(r'^reserva/request/(?P<pk>\d+)$', confirm_reservation_request, name="confirm_reservation_request"),
    url(r'^reserva/delete/(?P<pk>\d+)$', reservadelete, name="reservadelete"),
    url(r'^reserva/reservaformedit/(?P<pk>\d+)$', reservaformedit, name="reservaformedit"),
    url(r'^reserva/reservation_notification/(?P<pk>\d+)$', reservation_notification, name="reservation_notification"),
    url(r'^reservaform$', reservar, name="reservaform"),
    url(r'^reservasave$', ReservaCreate.as_view(), name="reservasave"),
    url(r'^get_salas_reserva$', get_salas_reserva, name="get_salas_reserva"),
    url(r'^reserva_resume$', reserva_resume, name="reserva_resume"),
    url(r'^$',  ihome, name="home"),
    url(r'^sala$', RoomList.as_view(), name="salas"),
    url(r'^sala/administrar$', RoomCreate.as_view(), name="sala_administrar"),
    url(r'^sala/administrar/(?P<pk>\d+)$', RoomEdit.as_view(), name="sala_administrar_edit"),
    url(r'^sala/eliminar/(?P<pk>\d+)$', RoomDelete.as_view(), name="sala_administrar_delete"),    
    url(r'^insumo$', iinsumo, name="insumos"),
    url(r'^insumo/administrar$', supply_new, name="insumos_administrar"),
    url(r'^insumo/administrar/(?P<pk>\d+)$', supply_edit, name="insumos_administrar_edit"),
    url(r'^insumo/eliminar/(?P<pk>\d+)$', supply_delete, name="insumos_administrar_delete"),
    url(r'^usuario$', UserList.as_view(), name="usuarios"),
    url(r'^usuario/administrar$', UserCreate.as_view(), name="usuario_administrar"),
    url(r'^usuario/eliminar/(?P<pk>\d+)$', UserDelete.as_view(), name="usuario_administrar_delete"),
]

hcmfront_prueba/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.hcmfront_app.urls', namespace="hcmfront_app")), 
]

apps/hcmfront_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.

def index(request):
	return HttpResponse("Hola Josue")

apps/hcmfront_app/views/account.py
from django.views.generic import View
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import logout
from django.shortcuts import render
class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('hcmfront_app:loginf'))

apps/hcmfront_app/views/home.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from apps.hcmfront_app.models import Reservation, Supply
from django.core.urlresolvers import reverse_lazy
from datetime import datetime
@login_required
def index(request):
	if request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:reservas')	

	reservations = Reservation.objects.filter(user = request.user, date__gte = datetime.now())
	context = {'reservations':reservations}
	return render(request, "home/index.html", context)

apps/hcmfront_app/views/insumo.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from apps.hcmfront_app.forms import SupplyForm
from apps.hcmfront_app.models import Supply
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
	if not request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:home')

	supplies = Supply.objects.all()
	context = {'supplies':supplies}
	return render(request, "insumo/index.html", context)

@login_required
def supply_new(request):
	if not request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:home')

	showerr = False
	if request.method == 'POST':
		form = SupplyForm(request.POST)
		if form.is_valid():
			form.save()
			return 	redirect('hcmfront_app:insumos')
		else:
			showerr = True
	else:
		form = SupplyForm()

	return render(request, "insumo/insumo_form.html", {'form': form, 'showerr': showerr})

@login_required
def supply_edit(request, pk):
	if not request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:home')

	supply = get_object_or_404(Supply, pk=pk) 
	if supply.id == 1 or supply.id == 2:
		return 	redirect('hcmfront_app:insumos')
	showerr = False
	if request.method == 'GET':
		form = SupplyForm(instance=supply)
	else:
		form = SupplyForm(request.POST, instance=supply)
		if form.is_valid():
			form.save()
			return 	redirect('hcmfront_app:insumos')
		else:
			showerr = True	
	return render(request, "insumo/insumo_form.html", {'form': form, 'showerr': showerr})	

@login_required
def supply_delete(request, pk):
	if not request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:home')
			
	supply = get_object_or_404(Supply, pk=pk) 
	if supply.id == 1 or supply.id == 2:
		return 	redirect('hcmfront_app:insumos')	
	if request.method == 'POST':
		supply.delete()
		return 	redirect('hcmfront_app:insumos')
	return render(request, "insumo/insumo_delete.html", {'supply': supply})	

apps/hcmfront_app/views/reserva.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from apps.hcmfront_app.models import Reservation_Request, Reservation, Notification, Supply, Room, Reservation_Priority,Reservation_Status
from apps.hcmfront_app.forms import ReservationForm, ReservationFormEdit
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, View
from django.core.urlresolvers import reverse_lazy
from django.template.loader import render_to_string
from apps.hcmfront_app.rooms_reservation import Rooms_Reservation
import json, datetime

@login_required
def index(request):
	context = {}
	if request.user.groups.filter(pk=1).exists():
		context["eventos"] = Reservation.objects.filter(date__gte = datetime.datetime.now())
	return render(request, "reserva/index.html", context)

class ReservaCreate(LoginRequiredMixin, CreateView):
	model= Reservation
	form_class = ReservationForm
	success_url = reverse_lazy('hcmfront_app:home')

	def dispatch(self, *args, **kwargs):
		if self.request.user.groups.filter(pk=1).exists():
			return 	redirect('hcmfront_app:reservas')
		return super(ReservaCreate, self).dispatch(*args, **kwargs)		

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		if not request.POST["rsv"] == "0":
		 	reservation = Reservation.objects.get(pk=request.POST["rsv"])
			dat = reservation.date.strftime('%d/%m/%Y')
			t1 = reservation.hour_from.strftime('%H:%M')
			t2 = reservation.hour_to.strftime('%H:%M')
			priority = Reservation_Priority.objects.get(id = request.POST["priority"])
			msj = ("El usuario "+ request.user.username +" ha solicitado la asignacion de la Reservacion: Sala " + reservation.room.name + ", con fecha " + dat +" de " + t1 + " a " + t2 +". Prioridad: " + priority.name + ".")
			noti = Notification(message=msj, type_noti=2 )
			noti.save()	
		 	rr = Reservation_Request(reservation = reservation, user = request.user, notification=noti)
		 	rr.save()
		else:
			if form.is_valid():
				obj = form.save(commit=False)
				obj.user = request.user
				obj.status = Reservation_Status(id=3)
				obj.save()
				form.save_m2m()						
				
		return HttpResponseRedirect(self.get_success_url())		

@login_required
def reservar(request):
	if request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:reservas')

	html = render_to_string('reserva/reserva_form.html')
	return HttpResponse(html)	

@login_required
def reservaformedit(request, pk):
	if not request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:home')

	reservation = Reservation.objects.get(pk=pk)

	if request.method == 'POST':
		form = ReservationFormEdit(request.POST)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.user = reservation.user
			obj.id = reservation.id
			obj.status = reservation.status
			obj.hour_from = reservation.hour_from
			obj.hour_to = reservation.hour_to
			obj.date = reservation.date
			obj.save()
			form.save_m2m()
		return redirect('hcmfront_app:reservas')	

	priorities = Reservation_Priority.objects.all()
	supplies = Supply.objects.filter(room__id=reservation.room.id)
	context = {'reservation': reservation, 'supplies' : supplies, 'priorities':priorities}
	html = render_to_string('reserva/reserva_formedit.html', request=request, context=context)
	return HttpResponse(html)		

@login_required
def get_salas_reserva(request):	
	if request.user.groups.filter(pk=1).exists():
		return 	HttpResponse()

	rooms_reservation = Rooms_Reservation(request.GET["date"], request.GET["from"], request.GET["to"], request.GET["quantity"]) 
	rooms = rooms_reservation.get_rooms_ordered()
	html = render_to_string('reserva/sala_select.html', {'rooms':rooms}, request=request)
	return HttpResponse(html)

@login_required
def reserva_resume(request):
	if request.user.groups.filter(pk=1).exists():
		return 	HttpResponse('hcmfront_app:reservas')	
	room = Room.objects.get(id=request.GET["room_id"])
	supplies = Supply.objects.filter(room__id=request.GET["room_id"])
	priorities = Reservation_Priority.objects.all()
	reservation = Reservation.objects.filter(pk=request.GET["rsv"]).first()
	if reservation:
		dat = reservation.date.strftime('%Y-%m-%d')
		t1 = reservation.hour_from.strftime('%H:%M')
		t2 = reservation.hour_to.strftime('%H:%M')
		html = render_to_string('reserva/reserva_resume.html', request=request, context= {'rsv':reservation.id,'date':dat,'supplies': supplies,'from': t1,'to': t2,'quantity': request.GET["quantity"], 'room' : room,'priorities':priorities })
	else:
		html = render_to_string('reserva/reserva_resume.html', request=request, context= {'rsv':0,'date':request.GET["date"],'supplies': supplies,'from': request.GET["from"],'to': request.GET["to"],'quantity': request.GET["quantity"], 'room' : room,'priorities':priorities })
	return HttpResponse(html)	

@login_required
def confirm_reservation(request, pk):
	reservation = get_object_or_404(Reservation, pk=pk)
	if not reservation.status.id == 3 or not (reservation.user == request.user or request.user.groups.filter(pk=1).exists()):
		return 	redirect('hcmfront_app:home')

	if request.method == 'POST':
		reservation.status = Reservation_Status(id=4)
		reservation.save()
		return 	redirect('hcmfront_app:home')
	return render(request, "reserva/confirmar.html", {'reservation': reservation})		

@login_required
def reservation_notification(request, pk):
	noti = get_object_or_404(Notification, pk=pk)
	if noti.checked:
		return 	redirect('hcmfront_app:home')
	noti.checked = True
	noti.save()
	return render(request, "reserva/reserva_notification.html", {'notification': noti})	
		

@login_required
def confirm_reservation_request(request, pk):
	reservation_req = Reservation_Request.objects.get(notification__id=pk)
	if not request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:home')
	print reservation_req.notification.checked
	if reservation_req.notification.checked:
		return 	redirect('hcmfront_app:reservas')		
		
	if request.method == 'POST':
		noti = Notification.objects.get(id=pk)
		noti.checked = True
		noti.user_check = request.user
		noti.save()

		if request.POST["th"] == "1":
			reservation = Reservation.objects.get(id=reservation_req.reservation.id)
			dat = reservation.date.strftime('%d/%m/%Y')
			t1 = reservation.hour_from.strftime('%H:%M')
			t2 = reservation.hour_to.strftime('%H:%M')
			msj = ("Su Reservacion de la Sala " + reservation.room.name + ", con fecha " + dat +" de " + t1 + " a " + t2 +" ha sido asignada a otro usuario.")
			noti = Notification(user_check=reservation.user, message=msj, type_noti=1 )

			reservation.user = reservation_req.user
			reservation.save()
			noti.save()

		return 	redirect('hcmfront_app:reservas')
	return render(request, "reserva/reserva_request_confirm.html", {'notification': reservation_req.notification})	


@login_required
def reservadelete(request, pk):
	if not request.user.groups.filter(pk=1).exists():
		return 	redirect('hcmfront_app:home')
	reservation = get_object_or_404(Reservation, pk=pk)
	if request.method == 'POST':
		dat = reservation.date.strftime('%d/%m/%Y')
		t1 = reservation.hour_from.strftime('%H:%M')
		t2 = reservation.hour_to.strftime('%H:%M')
		msj = ("Su Reservacion de la Sala " + reservation.room.name + ", con fecha " + dat +" de " + t1 + " a " + t2 +" ha sido eliminada.")
		noti = Notification(user_check=reservation.user, message=msj, type_noti=1 )
		noti.save()
		reservation.delete()
		return 	redirect('hcmfront_app:reservas')
	return render(request, "reserva/reserva_delete.html", {'reservation': reservation})			

apps/hcmfront_app/views/sala.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.hcmfront_app.models import Room
from apps.hcmfront_app.forms import RoomForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

class RoomList(LoginRequiredMixin, ListView):
	model= Room
	template_name= "sala/index.html"

	def dispatch(self, *args, **kwargs):
		if not self.request.user.groups.filter(pk=1).exists():
			return 	redirect('hcmfront_app:home')
		return super(RoomList, self).dispatch(*args, **kwargs)	

class RoomCreate(LoginRequiredMixin, CreateView):
	model= Room
	form_class = RoomForm
	template_name= "sala/sala_form.html"
	success_url = reverse_lazy('hcmfront_app:salas')

	def dispatch(self, *args, **kwargs):
		if not self.request.user.groups.filter(pk=1).exists():
			return 	redirect('hcmfront_app:home')
		return super(RoomCreate, self).dispatch(*args, **kwargs)	

	def form_invalid(self, form):
		return render(self.request, "sala/sala_form.html", {'form': form, 'showerr': True})

class RoomEdit(LoginRequiredMixin, UpdateView):
	model= Room
	form_class = RoomForm
	template_name= "sala/sala_form.html"
	success_url = reverse_lazy('hcmfront_app:salas')	

	def dispatch(self, *args, **kwargs):
		if not self.request.user.groups.filter(pk=1).exists():
			return 	redirect('hcmfront_app:home')
		return super(RoomEdit, self).dispatch(*args, **kwargs)	

	def form_invalid(self, form):
		return render(self.request, "sala/sala_form.html", {'form': form, 'showerr': True})	

class RoomDelete(LoginRequiredMixin, DeleteView):
	model= Room
	template_name= "sala/sala_delete.html"
	success_url = reverse_lazy('hcmfront_app:salas')	

	def dispatch(self, *args, **kwargs):
		if not self.request.user.groups.filter(pk=1).exists():
			return 	redirect('hcmfront_app:home')
		return super(RoomDelete, self).dispatch(*args, **kwargs)	

apps/hcmfront_app/views/usuario.py
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User, Group
from apps.hcmfront_app.forms import UserForm
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

class UserList(LoginRequiredMixin, ListView):
	model= User
	template_name= "usuario/index.html"	

	def dispatch(self, *args, **kwargs):
		if not self.request.user.groups.filter(pk=1).exists():
			return 	redirect('hcmfront_app:home')
		return super(UserList, self).dispatch(*args, **kwargs)	

class UserCreate(LoginRequiredMixin, CreateView):
	model= User
	template_name= "usuario/user_form.html"	
	form_class = UserForm
	success_url = reverse_lazy('hcmfront_app:usuarios')

	def dispatch(self, *args, **kwargs):
		if not self.request.user.groups.filter(pk=1).exists():
			return 	redirect('hcmfront_app:home')
		return super(UserCreate, self).dispatch(*args, **kwargs)	

	def post(self, request, *args, **kwargs):
		self.object = self.get_object
		form = self.form_class(request.POST)
		if form.is_valid():
			g = Group.objects.get(pk = request.POST["group"])
			user = form.save()
			if g.id == 1:
				user.is_staff =True
				user.is_superuser =True		
				user.save()	
			g.user_set.add(user.id)	
			return HttpResponseRedirect(self.get_success_url())
		else:
			return self.render_to_response(self.get_context_data(form=form, context= {'showerr': True}))

	def form_invalid(self, form):
		return render(self.request, "usuario/user_form.html", {'form': form, 'showerr': True})	

class UserDelete(LoginRequiredMixin, DeleteView):
	model= User
	template_name= "usuario/user_delete.html"
	success_url = reverse_lazy('hcmfront_app:usuarios')
	
	def dispatch(self, *args, **kwargs):
		if not self.request.user.groups.filter(pk=1).exists():
			return 	redirect('hcmfront_app:home')
		return super(UserDelete, self).dispatch(*args, **kwargs)	

apps/hcmfront_app/templates/sala/index.html
{% extends 'base/base.html'%}
{% load staticfiles %}
{% block title %} Salas de Reuniones {% endblock %}
{% block navegacion  %} 
<li class="active">
	Salas de Reuniones	
</li>
{% endblock %}
{% block nuevo %} 
	<a href="{% url 'hcmfront_app:sala_administrar' %}" class="btn_topbar btn btn-info">Nueva</a>
{% endblock %}
{% block contenido %} 
<div class="page-header">
	<h1>
		Listado de Sala de Reuniones
	</h1>
</div>
<div class="row">
	<div class="col-xs-12">
		<table id="room_table" class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Capacidad</th>
					<th>Horario</th>
					<th></th>
				</tr>
			</thead>
			<tbody>	
				{% if object_list %}
					{% for room in object_list %}
						<tr>
							<td>{{room.name}}</td>
							<td>{{room.capacity}}</td>
							<td>{{room.hour_from}} a {{room.hour_to}}</td>
							<td style="width:10%">
								<div class="hidden-sm hidden-xs btn-group">
									<a href="{% url 'hcmfront_app:sala_administrar_edit' room.id %}" class="btn btn-xs btn-info" data-rel="tooltip" title="Editar">
										<i class="ace-icon fa fa-pencil bigger-120"></i>
									</a>
									<a href="{% url 'hcmfront_app:sala_administrar_delete' room.id %}" class="btn btn-xs btn-danger" data-rel="tooltip" title="Eliminar">
										<i class="ace-icon fa fa-trash-o bigger-120"></i>
									</a>
								</div>

								<div class="hidden-md hidden-lg">
									<div class="inline pos-rel">
										<button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
											<i class="ace-icon fa fa-cog icon-only bigger-110"></i>
										</button>

										<ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
											<li>
												<a href="{% url 'hcmfront_app:sala_administrar_edit' room.id %}" class="tooltip-success" data-rel="tooltip" title="Editar">
													<span class="green">
														<i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
													</span>
												</a>
											</li>

											<li>
												<a href="{% url 'hcmfront_app:sala_administrar_delete' room.id %}" class="tooltip-error" data-rel="tooltip" title="Eliminar">
													<span class="red">
														<i class="ace-icon fa fa-trash-o bigger-120"></i>
													</span>
												</a>
											</li>
										</ul>
									</div>
								</div>
							</td>
						</tr>					
					{% endfor %}
				{% endif %}
			</tbody>
		</table>
	</div>
</div>
{% endblock %}

{% block extrajs %} 
	<script src="{% static 'js/dataTables/jquery.dataTables.js' %}"></script>
	<script src="{% static 'js/dataTables/jquery.dataTables.bootstrap.js' %}"></script>
	<script src="{% static 'js/dataTables/extensions/TableTools/js/dataTables.tableTools.js' %}"></script>
	<script src="{% static 'js/dataTables/extensions/ColVis/js/dataTables.colVis.js' %}"></script>
	<script type="text/javascript">
		jQuery(function($) {
			var oTable1 = 
			$('#room_table')
			.dataTable( {
				bAutoWidth: false,
				"aaSorting": [],
				"language": {
            		"url": "{% static 'js/dataTables/es.json' %}"
        		}
		    } );
		});
	</script>	
{% endblock %}

apps/hcmfront_app/templates/sala/sala_delete.html
{% extends 'base/base.html'%}
{% block title  %} Eliminar Sala de Reuniones {% endblock %}
{% block navegacion %} 
<li>
	<a href="{% url 'hcmfront_app:salas' %}">Salas de Reuniones</a>	
</li>
<li class="active">
	Eliminar Sala de Reuniones
</li>
{% endblock %}

{% block contenido %} 
<form method="POST" class="form-horizontal" role="form">
	{%csrf_token%}
	<h3>¿Desea eliminar la Sala de Reuniones: {{object.name}}?</h3>
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit">
				<i class="ace-icon fa fa-check bigger-110"></i>
				Si, eliminar
			</button>

			&nbsp; &nbsp; &nbsp;
			<a href="{% url 'hcmfront_app:insumos' %}" class="btn" >
				<i class="ace-icon fa fa-undo bigger-110"></i>
				Cancelar
			</a>

		</div>
	</div>	
</form>
{% endblock %}

apps/hcmfront_app/templates/sala/sala_form.html
{% extends 'base/base.html'%}
{% load staticfiles %}
{% block extracss %} 
	<link rel="stylesheet" href="{% static 'css/bootstrap-timepicker.css' %}" />
{% endblock %}
{% block title  %} Administrar Salas de Reuniones {% endblock %}
{% block navegacion %} 
<li>
	<a href="{% url 'hcmfront_app:salas' %}">Salas de Reuniones</a>	
</li>
<li class="active">
	Administrar
</li>
{% endblock %}

{% block contenido %} 
<form method="POST" class="form-horizontal" role="form">
	{%csrf_token%}
	{% if  showerr%}
		<div class="alert alert-danger">
			<button class="close" data-dismiss="alert">
				<i class="ace-icon fa fa-times"></i>
			</button>
			Error de Validación!
			<ul>
				{% for field, errors in form.errors.items %}
    				{% for error in errors %}
    					<li>{{error}}</li>
					{% endfor %}
				{% endfor %}
			</ul>
		</div>
	{% endif %}
	<div class="form-group">
		<label class="col-sm-1 control-label no-padding-right" for="txtname"> {{form.name.label}} </label>
		<div class="col-sm-11">
			{{form.name}}
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-1 control-label no-padding-right" for="txtlocation"> {{form.location.label}} </label>
		<div class="col-sm-11">
			{{form.location}}
		</div>
	</div>	
	<div class="form-group">
		<label class="col-sm-1 control-label no-padding-right" for="txtcapacity"> {{form.capacity.label}} </label>
		<div class="col-sm-3">
			{{form.capacity}}
		</div>
		<label class="col-sm-1 control-label no-padding-right" for="txthour_from"> {{form.hour_from.label}} </label>
		<div class="col-sm-3">
			{{form.hour_from}}
		</div>		
		<label class="col-sm-1 control-label no-padding-right" for="txthour_to"> {{form.hour_to.label}} </label>
		<div class="col-sm-3">
			{{form.hour_to}}
		</div>		
	</div>	
	<div class="form-group">
		<div class="row">
			<div class="col-xs-12"> 
				<div class="page-header">

					<h1>
						Insumos
					</h1>
				</div>	

				<div class="row">
					<div class="col-xs-12 id_supply" >
						{% for chk in form.supply %}
							<label for="{{ chk.id_for_label }}">
								{{chk.tag}}
								<span class="lbl">{{ chk.choice_label  }} {{chk.tag.id}} </span>
							</label>
						{% endfor %}

					</div>
				</div>
			</div>
		</div>
	</div>				
		
	<div class="clearfix form-actions">
		<div class="col-md-offset-3 col-md-9">
			<button class="btn btn-info" type="submit">
				<i class="ace-icon fa fa-check bigger-110"></i>
				Guardar
			</button>

			&nbsp; &nbsp; &nbsp;
			<a href="{% url 'hcmfront_app:salas' %}" class="btn" >
				<i class="ace-icon fa fa-undo bigger-110"></i>
				Cancelar
			</a>
		</div>
	</div>	
</form>
{% endblock %}

{% block extrajs %} 
	<script src="{% static 'js/date-time/bootstrap-timepicker.js' %}"></script>
	<script src="{% static 'js/date-time/moment.js' %}"></script>
	<script src="{% static 'js/fuelux/fuelux.spinner.js' %}"></script>
	<script type="text/javascript">
	jQuery(function($) {
		$('#txthour_from').timepicker({
			minuteStep: 1,
			showSeconds: false,
			showMeridian: false,
			defaultTime: '8:00'
		}).next().on(ace.click_event, function(){
			$(this).prev().focus();
		});
		$('#txthour_to').timepicker({
			minuteStep: 1,
			showSeconds: false,
			showMeridian: false,
			defaultTime: '17:00'
		}).next().on(ace.click_event, function(){
			$(this).prev().focus();
		});	
		jQuery.each(jQuery(".chk"), function(i, v) { 
			if(v.value == 1 || v.value == 2)
			{
				jQuery(this).attr("checked", "checked");;
			}
		})
		$('#txtcapacity').ace_spinner({min:1,max:200,step:1, btn_up_class:'btn-info' , btn_down_class:'btn-info'})
		.closest('.ace-spinner'); 

	});
	jQuery(".chk").on("change", function() {
		if(jQuery(this).val() == "1" || jQuery(this).val() == "2")
		{
			jQuery(this).prop("checked", true);
		}
	})
	</script>
{% endblock %}